runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: actualbudget/actions
        path: actions
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      shell: bash
      run: |
        cd actions/reviews
        echo '::group::npm ci'
        npm ci
        echo '::endgroup::'
    - name: Run Traffico
      id: traffico
      shell: bash
      with:
        github-token: ${{ github.token }}
      run: node actions/reviews/traffico/index.js

